version: '3'
services:
  postgres_lumen_go:
    image: postgres:11
    container_name: go_lumen_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=go_lumen
    networks:
      - backend
  # Go App
  go:
    build: .
    container_name: go_service
    ports:
      - "4999:9090"
    networks:
      - backend
    depends_on:
      - postgres_lumen_go
  # Lumen Migration service
  lumen:
    build: ./lumen
    container_name: lumen_service
    ports:
      - "9000:9000"
    networks:
      - backend

networks:
  backend:
    driver: bridge